---
title: "Graph of lncRNA in gene cluster"
output:
    html_document:
        toc: TRUE
meta:
    exp_id: 20211028_09_lncRNAsInGeneClusters
    type: analyse
    modules:
        - R/4.1
---

# Environment setup

```{r setup}

library(tidyverse)
theme_set(theme_bw())

```

## Load cluster composition

```{r load}
coexp_clusters <- 
    read_tsv("data/clusters/genes_in_cluster.tsv") %>%
    filter(cluster_type == "coexp")

coexp_random_clusters_size <-
    read_tsv("data/clusters/coexp_random_cluster_size.tsv.gz")

plantiSMASH_clusters <- 
    read_tsv("data/clusters/genes_in_cluster.tsv") %>%
    filter(cluster_type == "plantiSMASH")

plantiSMASH_random_clusters_size <-
    read_tsv("data/clusters/plantiSMASH_random_cluster_size.tsv.gz")

```


# Coexp cluster

```{r coexp}


coexp_genes_in_cluster <-
    bind_rows(coexp_clusters, coexp_random_clusters_size) %>%
    filter(gene_type != "antisense") %>%
    mutate(cluster_type=if_else(cluster_type=="random_size", "random",
                                cluster_type),
           cluster_type=factor(cluster_type,
                               levels=c("random",
                                        "coexp"
                               )
                               )
           )

graph <-
    coexp_genes_in_cluster %>%
    mutate(coding = if_else(gene_type == "protein_coding", "coding", "noncoding")) %>%
    count(cluster_name, cluster_type, random_run, coding) %>%
    pivot_wider(names_from="coding", values_from="n") %>%
    # if NA it is because while counting we did not find any lncRNAs
    mutate(noncoding=!is.na(noncoding)) %>%
    count(cluster_type, random_run, noncoding) %>%
    group_by(cluster_type, random_run) %>%
    mutate(prop=n/sum(n)) %>%
    group_by(cluster_type, noncoding) %>%
    summarise(
        mean=mean(n),
        median=median(n),
        sd=sd(n),
        se=sd/sqrt(n()),
        prop_median=median(prop)
    ) %>%
    ggplot(aes(x=cluster_type, fill=noncoding, y=median)) +
    geom_col(position = position_dodge(.9)) +
    geom_errorbar(aes(ymin = median - sd, ymax = median + sd), position = position_dodge(.9), width=.2) +
    geom_text(aes(y=median/2, label=scales::percent(prop_median, accuracy=1)),
              position=position_dodge(.9)) +
    scale_fill_brewer(palette="Set1", "lncRNA in cluster") +
    xlab("") + ylab("number of cluster")
ggsave("out/clusters/new/coexp_lncRNAs_in_cluster.pdf", plot=graph, width=4, height=2)

```

# plantiSMASH clusters

```{r geneClusterLoad}

plantiSMASH_genes_in_cluster <-
    bind_rows(plantiSMASH_clusters, plantiSMASH_random_clusters_size) %>%
    filter(gene_type != "antisense") %>%
    mutate(cluster_type=if_else(cluster_type=="random_size", "random",
                                cluster_type),
           cluster_type=factor(cluster_type,
                               levels=c("random",
                                        "plantiSMASH"
                               )
                               )
           )

graph <-
    plantiSMASH_genes_in_cluster %>%
    mutate(coding = if_else(gene_type == "protein_coding", "coding", "noncoding")) %>%
    count(cluster_name, cluster_type, random_run, coding) %>%
    pivot_wider(names_from="coding", values_from="n") %>%
    # if NA it is because while counting we did not find any lncRNAs
    mutate(noncoding=!is.na(noncoding)) %>%
    count(cluster_type, random_run, noncoding) %>%
    group_by(cluster_type, random_run) %>%
    mutate(prop=n/sum(n)) %>%
    group_by(cluster_type, noncoding) %>%
    summarise(
        mean=mean(n),
        median=median(n),
        sd=sd(n),
        se=sd/sqrt(n()),
        prop_median=median(prop)
    ) %>%
    ggplot(aes(x=cluster_type, fill=noncoding, y=median)) +
    geom_col(position = position_dodge(.9)) +
    geom_errorbar(aes(ymin = median - sd, ymax = median + sd), position = position_dodge(.9), width=.2) +
    geom_text(aes(y=median/2, label=scales::percent(prop_median, accuracy=1)),
              position=position_dodge(.9)) +
    scale_fill_brewer(palette="Set1", "lncRNA in cluster") +
    xlab("") + ylab("number of cluster")
ggsave("out/clusters/new/plantiSMASH_lncRNAs_in_cluster.pdf", plot=graph, width=4, height=2)


```
