---
title: "Graph of lncRNA in gene cluster"
output:
    html_document:
        toc: TRUE
meta:
    exp_id: 20211029_04_lncRNAsInGeneClusters
    type: analyse
    modules:
        - R/4.1
---

# Environment setup

```{r setup}

library(tidyverse)
library(ggpubr)
theme_set(theme_bw())

```

## Load cluster composition

```{r load}
coexp_clusters <- 
    read_tsv("data/clusters/coexp_clusters.tsv.gz")

coexp_random_clusters_size <-
    read_tsv("data/clusters/coexp_random_cluster_size.tsv.gz")

plantiSMASH_clusters <- 
    read_tsv("data/clusters/plantiSMASH_clusters.tsv.gz")

plantiSMASH_random_clusters_size <-
    read_tsv("data/clusters/plantiSMASH_random_cluster_size.tsv.gz")

```


# Coexp cluster

Statistical test

```{r coexp_summary}


coexp_genes_in_cluster <-
    bind_rows(coexp_clusters, coexp_random_clusters_size) %>%
    filter(gene_type != "antisense") %>%
    mutate(cluster_type=factor(cluster_type,
                               levels=c("random",
                                        "coexp"
                               )
                               )
           )

coexp_lncRNAs_in_cluster_summary <-
    coexp_genes_in_cluster %>%
    mutate(coding = if_else(gene_type == "protein_coding", "coding", "noncoding")) %>%
    count(cluster_name, cluster_type, random_run, coding) %>%
    pivot_wider(names_from="coding", values_from="n") %>%
    # if NA it is because while counting we did not find any lncRNAs
    mutate(noncoding=!is.na(noncoding)) %>%
    count(cluster_type, random_run, noncoding) %>%
    group_by(cluster_type, random_run) %>%
    mutate(prop=n/sum(n)) %>%
    group_by(cluster_type, noncoding) %>%
    summarise(
        mean=mean(n),
        median=median(n),
        sd=sd(n),
        se=sd/sqrt(n()),
        prop_median=median(prop)
    )

coexp_chi_square <- chisq.test(
    c(
        # number of cluster with lncRNA
        coexp_lncRNAs_in_cluster_summary %>%
            filter(cluster_type == "coexp", noncoding) %>%
            pull(mean),
        # number of cluster without lncRNA
        coexp_lncRNAs_in_cluster_summary %>%
            filter(cluster_type == "coexp", !noncoding) %>%
            pull(mean)
    ),
    p=c(
        # proportion of random cluster with lncRNA
        coexp_lncRNAs_in_cluster_summary %>%
            filter(cluster_type == "random", noncoding) %>%
            pull(prop_median),
        # proportion of random cluster without lncRNA
        coexp_lncRNAs_in_cluster_summary %>%
            filter(cluster_type == "random", !noncoding) %>%
            pull(prop_median)
    )
)

coexp_lncRNAs_in_cluster_summary

print(coexp_chi_square)
print(coexp_chi_square$expected)

```

Graph

```{r}

graph <-
    coexp_lncRNAs_in_cluster_summary %>%
    ggplot(aes(x=cluster_type, fill=noncoding, y=median)) +
    geom_col(position = position_dodge(.9)) +
    geom_errorbar(aes(ymin = median - sd, ymax = median + sd), position = position_dodge(.9), width=.2) +
    geom_text(aes(y=median/2, label=scales::percent(prop_median, accuracy=1)),
              position=position_dodge(.9),size=6) +
    scale_fill_brewer(palette="Set1", "lncRNA in cluster") +
    annotate("text", x=1.5, y=120, label=str_c("\u03c7\u00B2     ", round(coexp_chi_square$p.value, 4))) +
    xlab("") + 
    ylab("number of cluster")+
    theme(axis.text=element_text(size=12))
print(graph)

ggsave("out/clusters/final/coexp_lncRNAs_in_cluster.pdf", plot=graph, width=6, height=4)

```

# plantiSMASH cluster

Statistical test

```{r plantiSMASH_summary}


plantiSMASH_genes_in_cluster <-
    bind_rows(plantiSMASH_clusters, plantiSMASH_random_clusters_size) %>%
    filter(gene_type != "antisense") %>%
    mutate(cluster_type=factor(cluster_type,
                               levels=c("random",
                                        "plantiSMASH"
                               )
                               )
           )

plantiSMASH_lncRNAs_in_cluster_summary <-
    plantiSMASH_genes_in_cluster %>%
    mutate(coding = if_else(gene_type == "protein_coding", "coding", "noncoding")) %>%
    count(cluster_name, cluster_type, random_run, coding) %>%
    pivot_wider(names_from="coding", values_from="n") %>%
    # if NA it is because while counting we did not find any lncRNAs
    mutate(noncoding=!is.na(noncoding)) %>%
    count(cluster_type, random_run, noncoding) %>%
    group_by(cluster_type, random_run) %>%
    mutate(prop=n/sum(n)) %>%
    group_by(cluster_type, noncoding) %>%
    summarise(
        mean=mean(n),
        median=median(n),
        sd=sd(n),
        se=sd/sqrt(n()),
        prop_median=median(prop)
    )

plantiSMASH_chi_square <- chisq.test(
    c(
        # number of cluster with lncRNA
        plantiSMASH_lncRNAs_in_cluster_summary %>%
            filter(cluster_type == "plantiSMASH", noncoding) %>%
            pull(mean),
        # number of cluster without lncRNA
        plantiSMASH_lncRNAs_in_cluster_summary %>%
            filter(cluster_type == "plantiSMASH", !noncoding) %>%
            pull(mean)
    ),
    p=c(
        # proportion of random cluster with lncRNA
        plantiSMASH_lncRNAs_in_cluster_summary %>%
            filter(cluster_type == "random", noncoding) %>%
            pull(prop_median),
        # proportion of random cluster without lncRNA
        plantiSMASH_lncRNAs_in_cluster_summary %>%
            filter(cluster_type == "random", !noncoding) %>%
            pull(prop_median)
    )
)

plantiSMASH_lncRNAs_in_cluster_summary

print(plantiSMASH_chi_square)
print(plantiSMASH_chi_square$expected)

```

Graph

```{r}

graph <-
    plantiSMASH_lncRNAs_in_cluster_summary %>%
    ggplot(aes(x=cluster_type, fill=noncoding, y=median)) +
    geom_col(position = position_dodge(.9)) +
    geom_errorbar(aes(ymin = median - sd, ymax = median + sd), position = position_dodge(.9), width=.2) +
    geom_text(aes(y=median/2, label=scales::percent(prop_median, accuracy=1)),
              position=position_dodge(.9),size=6) +
    scale_fill_brewer(palette="Set1", "lncRNA in cluster") +
    annotate("text", x=1.5, y=35, label=str_c("\u03c7\u00B2     ", round(plantiSMASH_chi_square$p.value, 4))) +
    xlab("") + ylab("number of cluster")+
    theme(axis.text=element_text(size=12))
print(graph)

ggsave("out/clusters/final/plantiSMASH_lncRNAs_in_cluster.pdf", plot=graph, width=6, height=4)

```
