---
title: "Combination of all H3K27me3 ChiP analysis from Thomas R. (per repetition and replicate)"
output:
    html_document:
        toc: TRUE
meta:
    exp_id: 20211025_04_H3K27me3_ChIP_Analysis_per_replicate.Rmd
    type: analyse
    modules:
        - R/4.1
---

```{r setup}

library(tidyverse)
library(readxl)
library(grafify)
library(ggResidpanel)
library(lme4)
library(emmeans)

theme_set(theme_bw())

#' Correct the genotype code to have something homogeneous.
#' 
#' @param data A data frame.
#'   The colunm genotype is expected and will be processed
#' @return A tibble containg with the corrected genotype code in the genotype
#' column
clean_genotype_code <- function(data){
    data %>%
    mutate(
        genotype = tolower(genotype),
        genotype = case_when(
            genotype == "col-0" ~ "col",
            genotype == "col 0" ~ "col",
            genotype == "rnai9.2" ~ "rnai92",
            genotype == "rnai 9.2" ~ "rnai92",
            genotype == "rnai mars 1" ~ "rnai92",
            genotype == "rnai3.8" ~ "rnai38",
            genotype == "rnai 3.8" ~ "rnai38",
            genotype == "rnai mars 2" ~ "rnai38",
            TRUE ~ genotype
        )
        )
}

```

Load and combine the data

```{r H3K27me3_data_import}
H3K27me3_data_1 <- 
  read_excel("data/ChIP/ChIP_all/H3K27me3_output_qPCR.xlsx") %>%
  clean_genotype_code %>%
  mutate(Cp=as.numeric(Cp),
         Position=ifelse(Position == "MRN1.promotor", "MRN1.promoter", Position),
         Position=str_replace(Position, "MHAL", "MARS"),
         repetition="A")

all_ChIP_data_2 <- 
  read_excel("data/ChIP/ChIP_all/H3K27me3_LHP1_Line2_.xlsx") %>%
  clean_genotype_code %>%
  mutate(Cp=as.numeric(Cp),
         condition=ifelse(condition == "K27", "H3K27me3", condition),
         Position=gene,
         Position=str_replace(Position, "MHAL", "MARS"),
         repetition="B") %>%
  dplyr::select(-gene)

all_ChIP_data_3 <- 
  read_excel("data/ChIP/Repet_all_TR/chip_all_TR.xlsx") %>%
  clean_genotype_code %>%
  mutate(Cp=as.numeric(Cp),
         Position=gene,
         Position=str_replace(Position, "MHAL", "MARS"),
         time=ifelse(time == 0, as.character(0), "4 hours"),
         repetition="C") %>%
  dplyr::select(-gene)

H3K27me3_data <-
    bind_rows(H3K27me3_data_1, all_ChIP_data_2, all_ChIP_data_3) %>%
    filter(condition %in% c("input", "IGG", "H3K27me3"),
           Position %in% c("MRN1.promoter", "CYP705A12.3'", "CYP705A12.5'", "CYP71A16.3'", "CYP71A16.5'", "intergenic1", "intergenic2", "MARS.5'", "MARS.3'", "MRN1.5'", "MRN1.3'")) %>%
    identity

```

Plot the Cp


```{r H3K27me3_Cp}

graph <- 
    ggplot(H3K27me3_data, aes(x=condition, y=Cp, color=genotype)) +
        geom_text(aes(label=str_c(repetition, replicate)),
                  position=position_jitter(height=0, width=.2), size=2) +
       facet_wrap(~Position+time) +
       scale_color_brewer(palette="Set1")
ggsave("out/ChIP_TB/H3K27me3_Cp.pdf", plot=graph, width=15, height=10)

write_tsv(H3K27me3_data, "out/H3K27me3_formated_Cp.tsv")

```

Normalise according to input and plot.

```{r input_normalisation}

#Data processing
H3K27me3_input <-
  H3K27me3_data %>% 
  filter(condition == "input") %>%
  mutate(Cp_input=Cp - log2(10)) %>%
  dplyr::select(-Cp, -condition)

H3K27me3_IP <-
    H3K27me3_data %>% 
    filter(condition != "input") %>%
    left_join(H3K27me3_input) %>%
    mutate(Percent_input = 2^-(Cp-Cp_input)*100) %>%
    identity

graph <- 
    ggplot(H3K27me3_IP, aes(x=condition, y=Percent_input, color=genotype)) +
    geom_text(aes(label=str_c(repetition, replicate)),
              position=position_jitter(height=0, width=.2), size=2) +
   facet_wrap(~Position+time, scale="free") +
   scale_color_brewer(palette="Set1")
ggsave("out/ChIP_TB/H3K27me3_per_time.pdf", plot=graph, width=15, height=10)

graph <- 
    ggplot(H3K27me3_IP, aes(x=time, y=Percent_input, color=genotype)) +
    geom_text(aes(label=str_c(repetition, replicate)),
              position=position_jitter(height=0, width=.2), size=2) +
   facet_wrap(~Position+condition, scale="free") +
   scale_color_brewer(palette="Set1")
ggsave("out/ChIP_TB/H3K27me3_per_antibody.pdf", plot=graph, width=15, height=10)

write_tsv(H3K27me3_IP, "out/H3K27me3_input_normalised.tsv")
```
Correct for IGG outlier.

Remove the point when IGG more than 100 percent of input.

```{r H3K27me3_outlier}
IGG_outlier <-
    H3K27me3_IP %>%
    filter(Percent_input > 100) %>%
    dplyr::select(genotype, replicate, time, Position, repetition)

H3K27me3_IP_filtered <-
    H3K27me3_IP %>%
    anti_join(IGG_outlier)
write_tsv(H3K27me3_IP_filtered, "out/H3K27me3_input_normalised_filtered.tsv")
```


Compute the enrichment and plot

```{r H3K27me3_enrichment}

H3K27me3_enrichment <-
    H3K27me3_IP_filtered %>%
    dplyr::select(-Cp, -Cp_input) %>%
    pivot_wider(names_from=condition, values_from=Percent_input) %>%
    mutate(H3K27me3_enrichment = H3K27me3 / IGG)

graph<- 
    ggplot(H3K27me3_enrichment, aes(x=time, y=H3K27me3_enrichment, color=genotype)) +
    geom_text(aes(label=str_c(repetition, replicate)),
              position=position_jitter(height=0, width=.2), size=2) +
   facet_wrap(~Position, scale="free") +
   scale_color_brewer(palette="Set1")
ggsave("out/ChIP_TB/H3K27me3_enrichment.pdf", plot=graph, width=6, height=8)
write_tsv(H3K27me3_enrichment, "out/H3K27me3_enrichment.tsv")

```
Try some stats on MRN1 promoter

```{r MRN1_promoter_stats}
H3K27me3_MRN1promoter <-
    H3K27me3_enrichment %>%
    filter(Position == "MRN1.promoter") %>%
    mutate(rep_id = str_c(repetition, replicate)) %>%
    identity

MRN1_lmer <-
    lmer(H3K27me3_enrichment ~ genotype * time + (1|rep_id),
         data=H3K27me3_MRN1promoter)

summary(MRN1_lmer)
resid_panel(MRN1_lmer)
anova(MRN1_lmer, type = "II")

emmeans(MRN1_lmer,
        pairwise ~ genotype|time,
        adjust="fdr",
        type="response")

```

Iterate across all position and calculate p-values.
Each replicate independent of the others.

```{r all_position_graph}
for (position in unique(H3K27me3_enrichment$Position)){
    H3K27me3_current <-
        H3K27me3_enrichment %>%
        mutate(rep_id = str_c(repetition, replicate)) %>%
        filter(Position == position)
    current_lmer <-
        lmer(log(H3K27me3_enrichment) ~ genotype * time + (1|rep_id),
             data=H3K27me3_current)
    #summary(current_lmer)
    current_plot <- resid_panel(current_lmer)
    current_anova <- anova(current_lmer, type = "II")
    current_emmeans <-
        emmeans(current_lmer,
                pairwise ~ genotype|time,
                adjust="fdr",
                type="response")
    current_test <-
        current_emmeans$contrast %>%
        as.data.frame %>%
        filter(str_detect(contrast, "col")) %>%
        mutate(genotype = str_replace(contrast, "col / ", "")) %>%
        dplyr::select(genotype, time, p.value)
    current_stats <-
        current_emmeans$emmeans %>%
        as.data.frame %>%
        left_join(current_test)
    current_stats$genotype <- factor(current_stats$genotype, levels=c("col", "rnai92", "rnai38"))

    graph <-
        ggplot(current_stats, aes(x=time, y=response, fill=genotype)) +
        geom_col(position=position_dodge(.9), color="black") +
        geom_errorbar(aes(ymin = response - SE, ymax = response + SE),
                      position=position_dodge(.9), width=.35) +
        geom_text(aes(label=scales::number(p.value, accuracy=0.001), y=response + SE + 2),
                  size=4, position=position_dodge(.9)) +
  theme(legend.position="none")+
  ylab("") +
  xlab("")+
        scale_fill_manual(breaks=genotype_metadata_root$genotype,
                     values=genotype_metadata_root$genotype_color,
                     labels=genotype_metadata_root$genotype_name,)+
  geom_hline(yintercept=1,linetype=2)+
  theme(axis.text=element_text(size=14))
    ggsave(str_c("out/ChIP_TB/NEWSIZE_H3K27me3_", position, ".pdf"), plot=graph, width=2, height=3)
}

#previous size: width=7, height=4

```
