---
title: "Compute correlation analysis in the different clusters"
output:
    html_document:
        toc: TRUE
meta:
    exp_id: 20211028_08_lncRNAsExpressionCorrelation
    type: analyse
    modules:
        - R/4.1
---

# Environment setup

```{r setup}

library(tidyverse)
library(ggpubr)

theme_set(theme_bw())

```
# Coexp clusters

```{r}

coexp_corr_info <-
    read_tsv("data/clusters/coexp_corr_info.tsv.gz")


graph <-
    coexp_corr_info %>%
    filter(lncRNA_cluster, gene_type == "coding/lncRNA") %>%
    group_by(cluster_name, cluster_type) %>%
    summarise(corr = max(corr)) %>%
    ggplot(aes(x=cluster_type, y=corr)) +
    geom_violin() +
    geom_boxplot(width = .2) +
    stat_compare_means(method="t.test",
                       comparisons=list(c("random", "full_coexp"),
                                        c("random", "coexp"),
                                        c("full_coexp", "coexp")
                                        ),
                       label="p.value",
                       bracket.size=.5) +
    xlab("") + 
    ylab("maximum lncRNA correlation")
ggsave("out/clusters/new/coexp_violin_max_lncRNA_correlation.pdf",
       plot = graph, width = 4, height = 5)

graph <-
    coexp_corr_info %>%
    filter(gene_type=="coding")%>%
    group_by(cluster_name, cluster_type, lncRNA_cluster) %>%
    summarise(corr = median(corr)) %>%
    ggplot(aes(x=str_c(cluster_type, lncRNA_cluster), y=corr, fill=lncRNA_cluster)) +
    geom_violin(position=position_dodge(.9), scale="width") +
    geom_boxplot(width = .2, position=position_dodge(.9)) +
    scale_fill_brewer(palette= "Accent") +
    stat_compare_means(method="t.test",
                       comparisons=list(c("randomFALSE", "randomTRUE"),
                                        c("coexpFALSE", "coexpTRUE"),
                                        c("full_coexpFALSE", "full_coexpTRUE"),
                                        c("randomTRUE", "coexpTRUE"),
                                        c("randomFALSE", "coexpFALSE"),
                                        c("randomTRUE", "full_coexpTRUE"),
                                        c("randomFALSE", "full_coexpFALSE")
                                        ),
                       label="p.value",
                       bracket.size=.5) +
    xlab("") + 
    ylab("median lncRNA correlation")
ggsave("out/clusters/new/coexp_violin_median_cluster_correlation.pdf",
       plot = graph, width = 6, height = 5)

```

# plantiSMASH clusters

```{r}

plantiSMASH_corr_info <-
    read_tsv("data/clusters/plantiSMASH_corr_info.tsv.gz")

graph <-
    plantiSMASH_corr_info %>%
    filter(lncRNA_cluster, gene_type == "coding/lncRNA") %>%
    group_by(cluster_name, cluster_type) %>%
    summarise(corr = max(corr)) %>%
    ggplot(aes(x=cluster_type, y=corr)) +
    geom_violin() +
    geom_boxplot(width = .2) +
    stat_compare_means(method="t.test",
                       comparisons=list(c("random", "plantiSMASH")),
                       label="p.value",
                       bracket.size=.5) +
    xlab("") + 
    ylab("maximum lncRNA correlation")
ggsave("out/clusters/new/plantiSMASH_violin_max_lncRNA_correlation.pdf",
       plot = graph, width = 3, height = 5)

graph <-
    plantiSMASH_corr_info %>%
    filter(gene_type=="coding")%>%
    group_by(cluster_name, cluster_type, lncRNA_cluster) %>%
    summarise(corr = median(corr)) %>%
    ggplot(aes(x=str_c(cluster_type, lncRNA_cluster), y=corr, fill=lncRNA_cluster)) +
    geom_violin(position=position_dodge(.9)) +
    geom_boxplot(width = .2, position=position_dodge(.9)) +
    scale_fill_brewer(palette= "Accent") +
    stat_compare_means(method="t.test",
                       comparisons=list(c("randomFALSE", "randomTRUE"),
                                        c("plantiSMASHFALSE", "plantiSMASHTRUE"),
                                        c("randomTRUE", "plantiSMASHTRUE"),
                                        c("randomFALSE", "plantiSMASHFALSE")
                                        ),
                       label="p.value",
                       bracket.size=.5) +
    xlab("") + 
    ylab("median lncRNA correlation")
ggsave("out/clusters/new/plantiSMASH_violin_median_cluster_correlation.pdf",
       plot = graph, width = 4, height = 5)
```

